---
  - name: Check if src repo exists
    stat: 
      path: "{{repo_path}}"
    register: src_repo
  
  - name: Clone from GitHub
    git:
      repo: git@github.ncsu.edu:sbhoyar/iTrust2-v4.git
      dest: "{{repo_path}}"
      accept_hostkey: yes
      key_file: /root/.ssh/id_rsa_github
    when: src_repo.stat.exists == False
    become: true

  - name: Configure git post-receive push options
    command: chdir="{{repo_path}}" git config --local push.pushOption {{jenkins_user}}
    when: src_repo.stat.exists == False
    become: true
  
  - name: Configure git post-receive push options
    command: chdir="{{repo_path}}" git config --local push.pushOption {{jenkins_password}} {{jenkins_password}}
    when: src_repo.stat.exists == False
    become: true
    
  - name: Create bare repository for hook
    command: git init --bare "{{repo_path}}build/jenkins.git/"
    become: true
    when: src_repo.stat.exists == False

  - name: Configure bare repo to receive push options
    git_config:
      name: receive.advertisePushOptions
      value: true
      scope: local
      repo: "{{repo_path}}build/jenkins.git/"
    become: true

  - name: Add jenkins remote url
    git_config:
      name: remote.jenkins.url
      value: build/jenkins.git/
      scope: local
      repo: "{{repo_path}}"
  
  - name: Add jenkins remote refs for jenkins
    git_config:
      name: remote.jenkins.fetch
      value: +refs/heads/*:refs/remotes/jenkins/*
      scope: local
      repo: "{{repo_path}}"
  
  - name: Copy post receive hook to jenkins
    copy:
      src: templates/post-receive
      dest: "{{repo_path}}build/jenkins.git/hooks/"
      mode: 0755

