---
  - name: Set the python interpreter to symlink (version 2.7) for jenkins_job module
    set_fact:
      ansible_python_interpreter: '/usr/bin/python'
    become: true
  
  - name: Install python-jenkins for jobs
    pip:
      name: python-jenkins

  - name: Create a jenkins job for checkbox using basic authentication
    jenkins_job:
      config: "{{ lookup('file', 'templates/pipelineJob.xml') }}"
      name: checkbox
      password: "{{jenkins_password}}"
      url: http://localhost:8081
      user: "{{jenkins_user}}"
      state: present
    become: true
    
  - name: Create a jenkins job for iTrust2 using basic authentication
    jenkins_job:
      config: "{{ lookup('file', 'templates/iTrustJenkinsConfig.xml') }}"
      name: itrust
      password: "{{jenkins_password}}"
      url: http://localhost:8081
      user: "{{jenkins_user}}"
      state: present
    become: true
  
  - name: Set the python interpreter back to version 3
    set_fact:
      ansible_python_interpreter: '/usr/bin/python3'
    become: true
