---  
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      
  - name: Add jenkins repository key
    apt_key:
     url: https://pkg.jenkins.io/debian/jenkins.io.key
     state: present
    become: true

  - name: Add jenkins repo list file into sources.list.d
    apt_repository:
     repo: deb http://pkg.jenkins.io/debian-stable binary/
     state: present
    become: true

  - name: Install java
    apt:
      name: 'openjdk-8-jre'
      state: present
      update_cache: yes    
    become: true  

  - name: Install Jenkins
    apt:
      name: 'jenkins'
      state: present
      update_cache: yes    
    become: true

  - name: Install Git
    apt:
      name: 'git'
      state: present
      update_cache: yes    
    become: true

  - name: Install Maven
    apt:
      name: 'maven'
      state: present
      update_cache: yes    
    become: true

  - name: Allow port 8080
    become: true
    ufw:
      rule: allow
      port: '8080'

  - name: Start the server
    service:
      name: jenkins
      state: started

  - name : Wait for the the jenkins service to start
    wait_for:
      port: 8080
      delay: 45    